<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="user">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="username" type="xs:string"/>
                <xs:element name="email" type="xs:string" />
                <xs:element name="password" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="follow">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="follower" type="xs:string" />
                <xs:element name="following" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="message">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sender" type="xs:string" />
                <xs:element name="receiver" type="xs:string" />
                <xs:element name="content" type="xs:string" />
                <xs:element name="timestamp" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="messages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sender" type="xs:string" />
                            <xs:element name="receiver" type="xs:string" />
                            <xs:element name="content" type="xs:string" />
                            <xs:element name="timestamp" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="response">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" type="xs:string" />
                <xs:element name="username" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
